### ISSUE TITLE
Babel plugin

### ISSUE THREAD

**Issue by wldcordeiro** [mindeavor/es-pipeline-operator#18]
Is it possible to have this as a Babel plugin? It's one thing to see snippets but I'd like to test it out and see how I like it in practice too.

**Comment by mindeavor** [comment]
https://twitter.com/markdalgleish/status/673604840086310912

I'm sure many would be interested! I would work on one if I had time, but I'm busy with work :(

**Comment by mindeavor** [comment]
So I looked into it, and it wasn't so bad to implement. I've written the code, now I just need help figuring out how to publish it for others to use https://github.com/mindeavor/babel/tree/pipeline-operator

**Comment by wldcordeiro** [comment]
@mindeavor I think you make a PR and add your plugin to the preset this matches (stage-0, 1, etc)

**Comment by barneycarroll** [comment]
@mindeavour awesome!

@wldcordeiro since version 6, Babel doesn't do anything at all unless you specify plugins. The presets are just bundled plugins. No?

**Comment by wldcordeiro** [comment]
@barneycarroll Yes but you should add your plugin to the specified preset as well as having the individual plugin. :smile: I admittedly don't have much experience though, I'd try the Babel slack channel.

**Comment by Gozala** [comment]
What the status of this ? @mindeavor is there any reason not to publish plugin into npm ? I would really try it out.

**Comment by Gozala** [comment]
Just found there is a pull request for babel:
https://github.com/babel/babel/pull/3159

After following a conversation on the pull request I think I know answer to my question, which is publishing it as a standalone plugin is not possible given that it requires changes to the babylon parser.

Babel is also not going to take this proposal has being presented to TC39 :(

**Comment by zwhitchcox** [comment]
Is there any way to do this without changing the parser?

**Comment by michaelmitchell** [comment]
I am using the bitwise operators << and >> to achieve both forward and backward piping for now.

https://github.com/michaelmitchell/babel-plugin-pipe-composition

**Comment by zwhitchcox** [comment]
@michaelmitchell Oh, that's cool!

**Comment by michaelmitchell** [comment]
I really wanted the pipe operators ever since I saw them in an F# tutorial not long ago however it doesn't look there is any progress at all in babel supporting <| and |> and I very rarely use bitwise operators anyway.

You can also still use the bitwise operators normally anyway by adding the "no pipe" directive at the top of the function.

I really like/want pipe backward in JS so I can do the following which is much nicer than the alternatives in my opinion.

`const remove = curry << function(state, pattern) {
  // something
}`

**Comment by zwhitchcox** [comment]
Clever workaround! I had never seen the backwards pipeline before

**Comment by hzoo** [comment]
We have a PR for the transform in the Babel repo: https://github.com/babel/babel/pull/6335 if anyone wants to try it out in the REPL / review

**Comment by PinkaminaDianePie** [comment]
Any updates on this? It's hard to say anything about usability of proposal without possibility to try it in your code :)
