### ISSUE TITLE
First class support for Promises

### ISSUE THREAD

**Issue by kwijibo** [mindeavor/es-pipeline-operator#21]
The pipeline operator could work like an infix version of [R.pipeP](http://ramdajs.com/docs/#pipeP), allowing asynchronous pipelines to have (nearly?) the same syntax as synchronous ones:
```
fs.readFile('./index.txt')
|> .split('\n')
    .map(fs.readFile)
|> Promise.all
|> .join("\n")
|> process.stdout.write
|> .catch(process.stderr.write)
```

**Comment by RangerMauve** [comment]
So far, with things like [async functions](https://github.com/tc39/ecmascript-asyncawait) and [async iteration](https://github.com/zenparsing/async-iteration) the fact that it's async is explicit (usually with the keyword). I don't think it makes sense to introduce an operator that's sometimes async and sometiems sync since it doesn't follow the duality seen in other parts of the language.

**Comment by mindeavor** [comment]
@RangerMauve is right, the operator should always be synchronous. However, I think it would be interesting to add syntactical support for usage with the keyword `yield`:

```js
// Assume fs.readFile is an `async` function
async function runTask () {
  './index.txt'
    |> yield fs.readFile
    |> file => file
       .split('\n')
       .map(fs.readFile)
    |> yield Promise.all
    |> all => all.join("\n")
    |> _ => console.log(_)
}
```

**Comment by mindeavor** [comment]
Wow, so it turns out this syntax already works as expected (at least in my babel plugin). No need to change anything; it's already supported :smile:

**Comment by RangerMauve** [comment]
^ Awesome!

**Comment by kwijibo** [comment]
In my proposal, the operator *is* synchronous; if any of the functions return a Promise, the final value will always be a Promise, ie, a value returned synchronously (unless an `await` is used).  The point of my suggestion is to reduce boilerplate and mental overhead when dealing with asynchrony. 

The `await` alternative has more boilerplate and more mental overhead than a regular Promises version:

```javascript
fs.readFile('./index.txt')
.then(file=> file.split('\n').map(fs.readFile))
.then(Promise.all)
.then(files=>files.join('\n'))
.then(process.stdout.write)
.catch(process.stderr.write)
```

**Comment by RangerMauve** [comment]
@kwijibo What's the cue that lets people know they're dealing with an async pipeline? Using `await` to wait for a promise to complete is definitely not mental overhead because it's obvious what's going on.

**Comment by kwijibo** [comment]
Hi @RangerMauve. Your concern is that asynchrony should be explicit, as with `async`/`await`, right? I don't think that's applicable here because the proposal is that 

`p = x |> f |> g` 

be equivalent to  `p = R.pipeP(f,g)(x)`, 

not `p = g(await f(x))`
`await` resolves the Promise to a final value asynchronously, `R.pipeP` composes a function that returns a Promise synchronously.

Supporting promises would mean something like, decorating each function in the pipeline with:
```javascript
const acceptPromise = func => arg =>  isPromise(arg)? arg.then(func) : func(arg)
```
before composing them.

My understanding of `|>` is that it's about composing the functions to the right of the first `|>`, then passing the value to the left of the first `|>` to the resulting function

So to answer your question "what's the cue that lets people know they're dealing with an async pipeline?": they're not. They're dealing with a function that may return a Promise, or a String, or a Boolean, or an Array, or ... 
This is exactly the same as any other javascript function; the only hint to what the return value is, is how it is used subsequently.
In the case of my example, the clues are the `.catch` at the end, and perhaps you just know that the `readFile` function returns a Promise.

**Comment by RangerMauve** [comment]
I see where you're coming from, but I don't think it makes sense unless it was always equivalent to `R.pipeP(f,g)(x)`. It seems like currently the pipeline operator is more equivalent to `R.pipe(f,g)(x)`. Magically choosing between on or the other based on whether promises are detected somewhere in the chain doesn't seem like an intuitive way to go. It might make sense to wait until the non-promise version of the pipeline operator gets accepted, and then propose an async pipeline operator which deals with promises by default
