### ISSUE TITLE
Piping streams?

### ISSUE THREAD

**Issue by ReinsBrain** [mindeavor/es-pipeline-operator#300]
What are the implications for using the new operators to pipe streams (like [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream))? Could it work similarly to bash piping?

**Comment by tabatkins** [comment]
There's no particular implication. Pipeline is just a convenience syntax for chaining expressions. If you can write something with pipeline, you can instead write it as several statements all assigning to a temp var and get the identical result.

There's no connection, besides thematically, between the pipeline operator and the "piping" of streams. They're just both referencing the abstract concept of a value being "piped thru" some transformations.
