### ISSUE TITLE
Shortcut for method call? 

### ISSUE THREAD

**Issue by naholyr** [mindeavor/es-pipeline-operator#35]
`|>.` cannot conflict with anything so we could consider `|> .identifier(...)` is the same as `|> _ => _.identifier(...)`.
Same for `[` by the way. 

This would greatly simplify the example:

```js
// Assume fs.readFile is an `async` function
async function runTask () {
  './index.txt'
    |> await fs.readFile
    |> .split('\n')
    |> .map(fs.readFile)
    |> await Promise.all
    |> .join("\n")
    |> console.log
}
```

**Comment by jasmith79** [comment]
I love this. But isn't this is identical to what the bind operator proposal accomplishes? Do we need to modify the pipe operator or just mix and match as needed?

**Comment by naholyr** [comment]
I can't even answer that as I did never understand how the unary form of `::` is expected to behave :')

**Comment by dallonf** [comment]
With the bind operator, I guess it would like this?

```
// Assume fs.readFile is an `async` function
async function runTask () {
  './index.txt'
    |> await fs.readFile
    :: String.prototype.split('\n')
    :: Array.prototype.map(fs.readFile)
    |> await Promise.all
    :: Array.prototype.join("\n")
    |> console.log
}```

So not the _same_ thing (`::` requires you to specify a function explicitly), but pretty close.

**Comment by jamen** [comment]
Hmm, thinking here.

Is this different from just putting the method call on the same line?:
```javascript
async function runTask () {
  './index.txt'
    |> (await fs.readFile).split('\n').map(fs.readFile)
    |> (await Promise.all).join("\n")
    |> console.log
}
```

**Comment by naholyr** [comment]
OK pretty cool, so this shortcut is in fact absolutely not required ;) it would be a useless syntactic sugar distracting from the cleaner solution which is the bind operator.

Thanks for lightening up my understanding of `::` by the way!
