### ISSUE TITLE
Promise sample: no, not significant

### ISSUE THREAD

**Issue by naholyr** [mindeavor/es-pipeline-operator#36]
You say about the last example that 

> If we wanted to add catchError-like functionality using ES6 and stay fluent, we would have to either extend Promise.prototype, or re-implement the Promise interface (as bluebird and others have done).

But it's not true at all, in reality the exact same goal can be achieved in the same way with standard API:

```js
fetchPlayers()
  .then( players => players.filter( p => p.score > 100 ).map( fetchGames ) )
  .then( games => Promise.all(games) )
  .then( processGames )
  .catch( catchError( ProcessError, err => [] ) )
  .then( forEach(g => console.log(g)) );

function catchError (ErrorClass, handler) {
  return function catcher (error) {
    if (error instanceof ErrorClass) return handler(error);
    else throw error;
  }
}

function forEach (fn) {  return array => array.forEach(fn);  }
```

It's even shorter and simpler this way. I really like this operator, but this example is clearly not a "significant" one ;)

**Comment by mindeavor** [comment]
That's a great point, I will remove it from the readme :)
