### ISSUE TITLE
Spread version?

### ISSUE THREAD

**Issue by c-dante** [mindeavor/es-pipeline-operator#38]
Would it make sense to include spread pipeline operator as well? Applies the value instead of calls? For instance, `~>`.

```js
let add = (a, b) => a + b
let x = [1, 2, 3]
  ~> (_, b, c) => [b + c, b * c]
  ~> add
// x = (2 + 3) + (2 * 3) = 5 + 6 = 11
```

**Comment by jasmith79** [comment]
You could solve that trivially with a function decorator:

```javascript

let spread = (fn) => {
  return function(arr) { //using function to preserve ctx for methods
    return fn.apply(this, arr);
  };
};
```

Now you can use with the pipe operator:

```javascript
let foo = () => [1,2,3];
let addArr = spread(add);
foo |> addArr; // 6
```

**Comment by c-dante** [comment]
Yeah, makes sense not to introduce a new operator for a decorator -- doubt there's benefit to having an `apply` and `call` version.
