### ISSUE TITLE
Alternate syntax

### ISSUE THREAD

**Issue by mindeavor** [mindeavor/es-pipeline-operator#4]
Although I wrote the proposal, I do recognize a potential objection: [functions with multiple arguments](https://github.com/mindeavor/es-pipeline-operator#functions-with-multiple-arguments).

Although to me using arrow functions is perfectly explicit and clear, for the sake of argument let's explore two possible alternatives to handling this situation.

## 1. Elixir-style Inlining

Elixir's pipeline operator is actually different than the original proposal you see in this repo (of which we will call **F# style**). Instead of simply calling the right-hand side with the left-hand side, it instead **inserts** the left-hand side as the first argument to the right:

```js
// F# style
run("hello") |> withThis(10);
// is equivalent to
withThis(10)( run("hello") );

// Elixir style
run("hello") |> withThis(10);
// is equivalent to
withThis( run("hello"), 10 );

//
// More complicated example
//
// F# style
run("hello") |> withThis(10) |> andThis(20);
// is equivalent to
andThis(20)( withThis(10)( run("hello") ) );

// Elixir style
run("hello") |> withThis(10) |> andThis(20);
// is equivalent to
andThis( withThis( run("hello"), 10 ), 20 );
```

### Pros / Cons

- :+1: Less function calls (2 vs 3)
- :+1: Compatible with much more of the JavaScript ecosystem
- :-1: Gives a new semantic meaning to what looks like a normal function call. For example, `withThis(10)` is no longer just calling that function with one argument
- :-1: Putting the left-hand side as the first argument to the right-hand side is pretty arbitrary.

## 2. Placeholder Arguments

Another alternative is to have a new syntax for "placeholder arguments" – basically, slots waiting to be filled by the next function call. For example:

```js
// Placeholder style
run("hello") |> withThis(10, #);
// is equivalent to
withThis( 10, run("hello") );

//
// More complicated example
//
run("hello") |> withThis(10, #) |> andThis(#, 20);
// is equivalent to
andThis( withThis( 10, run("hello") ), 20 );
```

### Pros / Cons

- :+1: Very explicit (no surprises)
- :+1: Less function calls
- :+1: Compatible with even more of the JavaScript ecosystem
- :-1: Requires more new syntax
- :-1: Usage of the hash operator (#) would probably be hard to define outside coupled use with pipeline operator (this problem could be avoided by simply making it illegal)

Any thoughts and feedback would be greatly appreciated. Even if you are reiterating some of the points I've made, it's important to express them so we can see what the community thinks. Thanks for reading.

**Comment by acdlite** [comment]
My initial impression is that these alternatives don't quite gel with how function application works in JavaScript. They make more sense in languages that have currying.

**Comment by mindeavor** [comment]
@acdlite I agree with you with respect to the Elixir-style syntax; what looks like a function call is no longer just a function call. However, I think the placeholder-style does look distinctly different enough to give the impression, "something else must be going on semantically, now".

**Comment by eplawless** [comment]
If it's necessary to extend to multi argument (I agree that arrow functions are easy to understand here) the # placeholder does make it clear that something new is happening.

What happens if you put two placeholders?

What do nested pipeline operators do with placeholders?

**Comment by seanstrom** [comment]
@mindeavor have you looked at [LiveScript](http://livescript.net/#functions)? It also has support for the `|>` operator and also implements the placeholder arguments.

**Comment by AriaMinaei** [comment]
Expanding on @mindeavor's comment, LiveScript has a simple syntax for partial application: `add(1, 2) == add(1, _)(2)`.

**Comment by mindeavor** [comment]
@eplawless Great points, this is something that would need to be worked out (assuming people are really against just using arrow functions).

@seanstrom @AriaMinaei Thank you for the links to LiveScript's prior art, it's good to know that others already find the `|>` operator useful. I would also love to have underscore as partial application, but as you and I know, underscore is a commonly used variable name in JS :)

**Comment by AriaMinaei** [comment]
@mindeavor How about dashes? `add(1, -, -)` As you see, they can be funny too :)

**Comment by seanstrom** [comment]
@eplawless 
> What happens if you put two placeholders" 

Do you mean what happens if we do:
```javascript
run("hello") |> withThis(1, #, #)
```
?

> What do nested pipeline operators do with placeholders?

Can you provide an example of what you mean?

**Comment by seanstrom** [comment]
@mindeavor yeah underscores could confused things, but LiveScript also implements the placeholder arguments in a way that doesn't reserve the `_` character. So doing `_.map` would still work.

**Comment by dralletje** [comment]
@seanstrom although the moment you actually want to pass underscore for some reason, you'd have to do it with another name. It would make it harder too debug, I think

**Comment by seanstrom** [comment]
@dralletje correct, I'm not sure if anyone has brought that to the LiveScript teams attention. It's probably one of those things where most LiveScript users use the prelude.

**Comment by eplawless** [comment]
@seanstrom 
Please excuse any errors, I'm about to go forage for coffee.

Yes, your example is what I meant. Should the result be stored in a temporary and passed in both places? If so, can that violate the normal order of operations? Should "run" be executed twice, instead?

Here's what I mean by nested pipeline operators:
```javascript
1234 |> (5678 |> bar(#))
```

I assume it binds to its nearest ancestor pipe operator in the AST (so, the second one).  Are there any problems with that?

@mindeavor
Do you know what the operator precedence of `|>` should be relative to `.` ?

**Comment by seanstrom** [comment]
Strictly going off of LiveScript,

Something like this:
```javascript
const add = (x, y, z) => x + y +z
var add3 = 1 |> add(2, #, #) // add(2, 1, #)
var result = add3(3)
```
So the left hand of operator would go into the first `#` argument slot. Since that function would still need one more argument, the piping expression would result in a function that takes that remaining argument and once received it would apply the whole thing.

Nested expressions like this:
```javascript
3 |> (1 |> add(2, # , #))
```
Would most likely be evaluated by precedence from the parens from left to right I believe.
So we would first evaluate `(1 |> add(2, #, #))` and then we would apply `3 |> add(2, 1, #)`.
Which is what I believe you were mentioning right?

**Comment by mindeavor** [comment]
> Do you know what the operator precedence of |> should be relative to . ?

I imagine the `|>` would have the lowest operator precedence, which would mean the `.` operator would happen first.

**Comment by dvlsg** [comment]
I agree that the arrow functions are explicit and clear. They seem like the most intuitive option to me, and would also allow for easy destructuring where necessary.

**Comment by Havvy** [comment]
Note that function piping is just syntactic sugar, so we could bikeshed on it all day.

Personally, I like the Elixir version, but then, I also write Elixir. The LiveScript version looks like it'd work too, but I'd rather see a keyword there rather than an `_` or `#`. As this is new syntax, it should be relatively easy to add a new keyword. Sort of like how `let` works.

**Comment by jasmith79** [comment]
What about restricting use to unary functions? Then it would be on the programmer to partially apply, would eliminate a lot of potential cognitive overhead.

**Comment by mindeavor** [comment]
@jasmith79 I agree, in fact that is the original proposal :)

**Comment by MiracleBlue** [comment]
I'm super, super excited about having a pipeline operator, but to just throw my two cents in here, I'd prefer the Elixir-style syntax.  I think the pipeline itself semantically describes enough of what is going on.  I don't feel the need to be super explicit about where the left-hand value is going.  It also makes it cleaner visually.  The only concern obviously would be learning curve for new users (especially ones not used to that kind of magic).

That's just my two cents, though.  Take it or leave it :)

**Comment by Havvy** [comment]
Another thing that could be done is waiting for a macro system in JS in the
future, and letting the pipe syntax just be a macro.

**Comment by mindeavor** [comment]
Perhaps more fuel to the fire: it looks like someone made an Elixir-style pipe operator pull request to CoffeeScript https://github.com/jashkenas/coffeescript/pull/4144

It seems to me the programming community at large is moving towards this functional programming direction.

**Comment by jamen** [comment]
Perhaps a different function definition to handle piped data (e.g. generators are `function*`) such as `function^`, `function~`, or whatever.

From there, piped data could be accessed through a special keyword (or maybe `this`?)

```javascript
const example = function^(arg) {
  return this + arg;
};

let test = 10
  |> example(5);

// test === 15
```

**Comment by barneycarroll** [comment]
@jamen that's the ES7 bind operator.

```
let test = 10::example( 5 )
```

Non-arrow functions can already have `this` applied, so plain old ES5 functions work fine.

**Comment by jamen** [comment]
@barneycarroll, yeah that's a good point (I didn't know about the bind operator either).  Now that I think about it, there isn't really a way to use lambdas with my method.


> Although to me using arrow functions is perfectly explicit and clear,

Arrow functions work perfectly then imo.  Is there a reason to add alternative ways to use it if we have a clear-cut way?

```javascript
const example = data1, data2 => {
  return data1 + data2;
};

let test = 10
  |> x => example(x, 5);
```

This seems perfectly fine.  There is no abstraction, you know what data is going where, and there is no new syntax besides the pipe operator.

**Comment by MiracleBlue** [comment]
My only concern with that is it's diverging from what many other languages
already do.  I'm always in favour of conforming to the common pattern where
it makes sense.

**Comment by jamen** [comment]
@MiracleBlue, that's a good point as well.  I suppose if there isn't really a big issue to begin with (at least in my opinion), we can at least make it similar to how it would be done in another language, to limit the learning curve I suppose.

**Comment by MiracleBlue** [comment]
Yeah I feel like that makes the most sense.  At the very least, if you're
coming from a language which already has this implemented, it makes it a
bit easier.

**Comment by seanstrom** [comment]
How does the Elixir way and the proposed Coffeescript way handle curried functions? Or any time we have a function that returns a function? For example I may have `{} |> buildFn(data)` and `buildFn` is suppose to return a function.

Also, what if I want to point the piped value to a certain argument slot? For example I may have functions that don't want to take the piped data as the first argument. At that point I would have to wrap my function, which is what we would do without the Elixir implementation.

**Comment by seanstrom** [comment]
Note that multi-parameters was brought up in the Elixir project https://github.com/elixir-lang/elixir/issues/1156. But it turns out it isn't a priority since the `|>` is a macro and can be tweaked by the programmer. Unfortunately we're not in the same position. So we need to make sure that we can easily handle:
* unary functions `10 |> _.identity`
* sort-of partially applied functions `10 |> Math.max(1)`
* functions that return functions `10 |> _.compose(f, g)`
* potentially n-ary functions through placeholders `reducerFn |> _.reduce(data, #, {})`

Anything that I missed?
Note that place holder arguments can essentially be a sugar towards currying/partially applying a n-ary function.

**Comment by MiracleBlue** [comment]
That's a good point, I didn't realise the Elixir version was an actual macro that could be adjusted.

**Comment by robbiespeed** [comment]
What about something like this:
```
let text = 'world' |> ('Hello', caps) |> addWords |> yell;
// text === 'Hello WORLD!!!'
```
Which would be the equivalent to: 
```
let text = yell(addWords('Hello', caps('world')));
```
No need for added keyword or placeholder

**Comment by seanstrom** [comment]
@robbiespeed what if we wanted to pipe to the second argument of a function that takes in three arguments?

**Comment by robbiespeed** [comment]
@seanstrom Are you talking about partially applied functions? Or just something like this:
```
let text = 'world' |> ('Hello', caps, reverse) |> addWords |> yell;
// equivalent of 
let text = yell(addWords('Hello', caps('world'), reverse('world')));
// text === 'Hello WORLD dlrow!!!'
```
If your talking about partially applied functions though, personally I don't think those should be something we try to handle with the pipeline operator and rather just make functions that return a function if not all arguments were met.

**Comment by jamen** [comment]
> potentially n-ary functions through placeholders reducerFn |> _.reduce(data, #, {})

Couldn't we just use a arrow function in this case?

```javascript
reducerFn 
  |> x => _.reduce(data, x, {})
```

That would eliminate the need for new syntax.

**Comment by seanstrom** [comment]
@robbiespeed 
I was talking about a scenario where I have 3 or more argument function and I want to pipe a value to an argument position that isn't the first or the last. For example:

```javascript
let takesThree = (x, y, z) => x + y * z
1 |> (10, #, 5) |> takesThree // takesThree(10,1,5)
```

The example uses the `#` but I did that only to show how I wanted to order the arguments.
As for the partially applied functions, I think we're in agreement on that. If they already ready to curry then just let them right?

**Comment by seanstrom** [comment]
@jamen 
We could totally use arrow functions in that case, since `#` would probably be sugar for that.
What's interesting is when you incorporate multiple placeholders. You could say:

```javascript
reducerFn |> (data |> _.reduce(#, #, {}))

// which is actually

reducerFn |> x => (data |> y => _.reduce(x, y))
```

**Comment by robbiespeed** [comment]
@seanstrom I don't think anyone should use pipe in that case... it's just a single level function call. Can you give me a case with multiple levels that wouldn't work with the proposed syntax?

Modified your example:
```
function double (x) { return 2*x }
function addThree (x, y, z)  { return x + y + z }
1 |> (10, double, 5) |> addThree // addThree(10,double(1),5)
```

**Comment by jamen** [comment]
```javascript
reducerFn |> (data |> _.reduce(#, #, {}))
```

I still think the arrow function's are better.  How would the interpreter know what order they're in? If we wanted them in a different order we would have to resort to arrow functions anyways.

I think arrow functions are more practical in the long run.

**Comment by seanstrom** [comment]
@robbiespeed 
I'm not sure what you mean by they shouldn't use `|>` in that case. It would be for control flow purposes.
In the above example, imagine `1` was a series of piped operations and now I wanted to pipe the result to a function that takes 3 arguments, but as the second argument.

```javascript
// result would be potentially several operations of |>

// placeholders
someVal
|> someFn
|> myFn(otherFn, #, {})

// arrow functions
someVal
|> someFn
result |> x => myFn(otherFn, x, {})

// your syntax -- this is what I want to do essentially
someVal
|> someFn
result |> (otherFn, result, {}) |> myFn
```

**Comment by seanstrom** [comment]
@jamen I believe the nearest value being piped would be applied to the nearest open slot.

```javascript
let add = (x, y, z) => x + y + z
3 |> (2 |> add(1, #, #)) // add(1,2,3)
```

Though this behavior is mostly based on LiveScript's implementation of placeholder arguments.
If you wanted to re-arrange the arguments you would need a new function, which to your point would mean we could just skip all the extra sugar and just go for wrapper functions. Ideally the placeholder syntax would just be shorthand for currying the function.

**Comment by robbiespeed** [comment]
@seanstrom okay so in that example, it seems like you want to pass a function as an argument to a function at the end of the pipe, and that's tricky with my proposed syntax. If we said that wrapping a function in braces made it a reference rather than a function to be applied to the pipe value: 
```
someVal
|> ((otherFn), someFn, {}) |> myFn
```

**Comment by seanstrom** [comment]
@robbiespeed 
You would run into a situation where wrapping something in parens wouldn't mean expression evaluation precedence. For example:

```javascript
let addWorld = str => str + " World"

someVal |> ((addWorld("Hello") + "!"), someFn, {}) |> myFn
// myFn("Hello World!", someFn(someVal), {})
```

**Comment by robbiespeed** [comment]
@seanstrom thinking about it some more I've realised my syntax would not be able to be parsed easily and optimized to es6. I think something like this would work however:
```
someVal
|> (otherFn, |> someFn, {}) |> myFn
```
or if you simply want to pipe the previous value:
```
someVal
|> someFn 
|> (otherFn, |> , {}) |> myFn
```

**Comment by seanstrom** [comment]
@robbiespeed 
Yeah I'm not sure about that syntax. It's definitely a new look/usage of the `|>` operator for me.
I'm a little pro place-holder arguments because it seems to be vetted by the LiveScript community.
But we could just adhere to using arrow functions for now and possibly adding a sugar syntax later.
I would be willing to handle it that way since I would love having `|>` in general.

**Comment by robbiespeed** [comment]
I'd much rather a keyword than a placeholder. And I find the syntax:
`value |> funcA |> funcB(1, result, 2)` confusing since typically when calling a function in the pipe we'd expect it to return a function.  

Would prefer:
`value |> funcA |> (1, result, 2) |> funcB`

Not sold on using arrow syntax in place of some added syntax specific to the case. Mostly because I'm not convinced rules could be written to reliably parse it to the equivalent performance of standard nested function calls.

**Comment by seanstrom** [comment]
Yeah i'm not convinced a keyword would be worth it, `_` in LiveScript is used for partially applying any function with or without the `|>` operator. It reads well there IMO, but we likely wouldn't be able to convince others to use `_`. Perhaps there's another character(s) that would somehow convey the intent of a placeholder.

Could you clarify your second statement about parsing the arrow functions? Do you mean the performance between functions with bounded contexts (this) and normal functions?

```javascript
let funcOne = function (x) { return function (y) { return x + y } }
let funcTwo = x => y => x + y
```

Like the performance between those two functions? If so I would think that would have to be an optimization by the run-time for when the function does use `this` or not. Which should mean that we wouldn't need custom rules for parsing things that are known function statements right? We would just leave the implementation up to the programmer. For now they could write the other version inlined or extract the function entirely.

```javascript
value
|> funcA
|> (function (result) { return funcB(otherStuff, result) })

// ---

let newFn = function (result) { return funcB(otherStuff, result) })
value |> funcA |> newFn
```

**Comment by robbiespeed** [comment]
@seanstrom No I mean in terms of using something like babel to compile the es7 down to es5/6, as well the fact that `funcC('fast', funcB(funcA('test')))` would perform better than `(x => funcC('slow', x))(funcB(funcA('test')))`. Ultimately I believe this statement from the proposal is misleading:
> Also, because the pipe operator's semantics are pure and simple, it could be possible for JavaScript engines to optimize away the arrow function

Arrow functions allow for some complex things to happen. It would add unneeded complexity to a javascript engine, if it were to first check if the arrow function does complex or simple things, then optimize if it only does simple things. What would be better IMO is to define a syntax where the simple things (or what we can already achieve with nested function calls) are accounted for.

**Comment by seanstrom** [comment]
@robbiespeed I believe you're pointing out two things there:

1. `=>` may be slower than just an ordinary function.
2. Any extra indirection would be slower than inlining the arguments to the function call.

Is this correct? I just want to make sure I'm on the same page here. 
I also now see why the syntax you were suggesting was the way it was, I believe you were trying to represent an easy to parse arguments list right?

**Comment by robbiespeed** [comment]
@seanstrom Yes to 2, but not to 1. Depending on implementation arrow functions should be just as fast as regular functions, the problem comes when your wrapping a function call in another function, it's wasted computing.

Yes that was the goal, to represent a clear arguments list for the next function in the pipe to use.

**Comment by seanstrom** [comment]
@robbiespeed Cool. I can see why an arguments tuple is better for illustrating that. Normally I would just go through currying the functions and eat the performance cost, since it would be negligible to me. But I can see why the performance cost or the added complexity in engine to optimize that would be a downer.

**Comment by mindeavor** [comment]
> Arrow functions allow for some complex things to happen. It would add unneeded complexity to a javascript engine...

I could be wrong, but my experience with writing compilers tells me the optimization would not be difficult; you would only need the extra logic when you see a pipe operator, and the transformation is entirely based on the AST. For example:

    run('task') |> result => process(result, true)

This could be optimized to:

    process( run('task'), true )

with zero consequences. The reason a "simple" arrow function is optimizable is because the body is a **single expression**; in any other case, the optimization would simply be skipped.

**Comment by barneycarroll** [comment]
Furthermore, arrow functions are 'unbindable': they have no `this` and cannot have `this` applied to them — any reference to `this` inside the immediate scope of an arrow will look up to the scope in which it is defined. I think it would be truer to say that arrow functions are much simpler than their traditional counterparts (and more 'optimisable' as a result).

**Comment by tabatkins** [comment]
Jumping in without reading most of the thread, sorry:

I rather like the placeholder syntax, as it seems useful when decoupled from pipeline as an extremely lightweight arrow function.  That is, `foo(1, #, 3)` just desugars to `x=>foo(1, x, 3)`.  That said, it's a savings of three characters, so it probably won't end up being worth it.

**Comment by mindeavor** [comment]
Ok, so my takeaway from this thread is that the placeholder syntax is not only unnecessary, but also a different issue (partial application). Elixir style is interesting, but I think in the long run piping to the end is more useful than piping to the beginning.

I've aggregated all these ideas into a new version of the pipeline operator. Let's move our discussion to the new issue: https://github.com/mindeavor/es-pipeline-operator/issues/20
