### ISSUE TITLE
Example seems incorrect (or confusing?)

### ISSUE THREAD

**Issue by aickin** [mindeavor/es-pipeline-operator#5]
Thanks for this proposal; seems really cool. I was confused by this example, though:

```javascript
var person = { score: 75 };

var newScore = person.score
  |> double
  |> score => add(7, score)
  |> validateScore

newScore //=> 107

// As opposed to: var newScore = add(7, validateScore( double(person.score) ))
```

Now I don't know if there's a mistake in the example or if the proposal itself confuses me, but it seems really odd that the functions nest in a different order than they are piped. I would think that they would nest in the same order, with the first piped function as the innermost one, namely:

```javascript
var newScore = validateScore(add(7, double(person.score) ));
```

Am I misunderstanding the example? Why do they neat in a different order for this case?

Thanks for all your great work!

**Comment by mindeavor** [comment]
Aha, that is a mistake, thank you for pointing it out. I will fix it now.

**Comment by pitaj** [comment]
I think either the example is incorrect or the ad opposed to is. 

:+1:

**Comment by aickin** [comment]
Awesome, thanks!
